<?php

/**
 * @file
 * Content Type Clone primary module file.
 */

/**
 * Reimplements the content type list table, addding a clone link.
 */
function content_type_clone_node_overview_types() {
  $types = node_type_get_types();
  $names = node_type_get_names();
  $field_ui = module_exists('field_ui') && user_access('administer fields');
  $header = array(t('Name'), t('Operations'));
  $rows = array();

  // Sort the list of content types by label instead of machine name.
  natcasesort($names);

  foreach ($names as $key => $name) {
    $type = $types[$key];
    $type_url_str = str_replace('_', '-', $type->type);
    $row = array(theme('node_admin_overview', array('name' => $name, 'type' => $type)));
    $links['configure'] = array(
      'title' => t('Configure'),
      'href' => 'admin/structure/types/manage/' . $type_url_str,
      'weight' => 0,
    );
    if ($field_ui) {
      $links['fields'] = array(
        'title' => t('Manage fields'),
        'href' => 'admin/structure/types/manage/' . $type_url_str . '/fields',
        'weight' => 5,
      );
      $links['display'] = array(
        'title' => t('Manage displays'),
        'href' => 'admin/structure/types/manage/' . $type_url_str . '/display',
        'weight' => 10,
      );
    }
    if ($type->module === 'node') {
      $links['delete'] = array(
        'title' => t('Delete'),
        'href' => 'admin/structure/types/manage/' . $type_url_str . '/delete',
        'weight' => 15,
      );
    }
    $links['clone'] = array(
      'title' => t('Clone'),
      'href' => 'admin/' . $type_url_str . '/clone/create',
      'weight' => 20,
    );
    $row[] = array(
      'data' => array(
        '#type' => 'operations',
        '#links' => $links,
      ),
    );

    $rows[] = $row;
  }

  $build['node_table'] = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
    '#empty' => t('No content types available. <a href="@link">Add content type</a>.', array('@link' => url('admin/structure/types/add'))),
  );

  return $build;
}

/**
 * Implements hook_menu().
 */
function content_type_clone_menu() {
  // Content type clone form url.
  $items['admin/%/clone/create'] = array(
    'title' => '',
    'access arguments' => array('administer content types'),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('content_type_clone_create_form', 1),
    'file' => 'includes/clone.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/structure/types/manage/%node_type/clone'] = array(
    'title' => 'Clone',
    'access arguments' => array('administer content types'),
    'page callback' => 'content_type_clone_menu_redirect',
    'file' => 'includes/page.admin.inc',
    'page arguments' => array(4),
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function content_type_clone_menu_alter(&$items) {
  $items['admin/structure/types']['page callback'] = 'content_type_clone_node_overview_types';
}
